### PR TITLE
CE-1607: Remove credentials from db connection error logging

### PR DESCRIPTION
**Pull request by edward-codecov**

### CODE REVIEW

**Comment by thomasrockhu** [comment]
@hootener is this one still relevant?

**Comment by hootener** [comment]
@thomasrockhu let's leave this one open a bit longer.

**Comment by hootener** [comment]
I'm considering closing this. I've tested it in several scenarios and it doesn't seem to properly obfuscate the username / password. I don't know how pressing of an issue this from a security perspective, honestly. These credentials are only exposed on enterprise installs to STDOUT and _only_ when the db configuration itself _is wrong_. 

We've had one ticket on this for enterprise, and tornpsql will be totally removed from active use with the move Codecov v5. It's tough to justify making changes to such a (currently) crucial, but so rarely updated and old dependency. I'm not sure if this fix is worth it. Any thoughts @thomasrockhu ?

**Review by hootener — CHANGES_REQUESTED** [review]
Rejecting this currently. See PR comment :point_up:

**Pull request closed without merging**
